export const defaultTheme = {
  fontFamily: 'Inter, "Segoe UI", system-ui, sans-serif',
  fontSize: 14,
  fontWeight: 500,
  headerFontSize: "0.78rem",
  headerFontWeight: 900,
  rowFontSize: "0.92rem",
  rowFontWeight: 500,
  headerHeight: 44,
  rowHeight: 42,
  cellPaddingInline: 12,
  cellPaddingBlock: 0,
  borderRadius: 12,
  iconSize: 16,
  background: "#ffffff",
  panelBackground: "#ffffff",
  panelStrongBackground: "#f8fafc",
  textColor: "#0f172a",
  mutedTextColor: "#64748b",
  headingColor: "#111827",
  borderColor: "#d8e1ef",
  primaryColor: "#2563eb",
  headerBackground: "#f8fafc",
  pinnedBackground: "#ffffff",
  hoverBackground: "#eff6ff",
  selectedBackground: "#dbeafe",
  selectedTextColor: "#0f172a",
  focusedCellColor: "#2563eb",
  alternateRowBackground: "#f8fafc",
  validationErrorColor: "#ef4444",
  changedColor: "#f59e0b",
  reviewedColor: "#22c55e",
  disabledOpacity: 0.48,
  shadow: "0 18px 48px rgba(15, 23, 42, 0.12)",
};
