const runtimeStyleId = "gridnexa-react-runtime-styles";

const runtimeStyles = `
.sg-grid-root,.sg-shell,.sg-toolbar,.sg-header,.sg-header-cell,.sg-row,.sg-cell{box-sizing:border-box}
.sg-shell{--gnx-bg:#fff;--gnx-panel:#fff;--gnx-panel-strong:#f8fafc;--gnx-text:#0f172a;--gnx-muted:#64748b;--gnx-heading:#111827;--gnx-border:#dbe3ef;--gnx-primary:#2563eb;--gnx-row-hover:#eff6ff;--gnx-header-bg:#f8fafc;--gnx-pinned-bg:#fff;--gnx-shadow:0 18px 48px rgba(15,23,42,.12);display:grid;gap:10px;width:100%;font:14px/1.45 Inter,"Segoe UI",system-ui,sans-serif;color:var(--gnx-text)}
.sg-shell[data-gnx-theme="dark"]{--gnx-bg:#070b18;--gnx-panel:#0f172a;--gnx-panel-strong:#111827;--gnx-text:#e5edf7;--gnx-muted:#9ca3af;--gnx-heading:#f8fafc;--gnx-border:rgba(148,163,184,.2);--gnx-primary:#60a5fa;--gnx-row-hover:rgba(96,165,250,.12);--gnx-header-bg:#0b1220;--gnx-pinned-bg:#080c18;--gnx-shadow:0 24px 70px rgba(4,8,20,.38)}
@media(prefers-color-scheme:dark){.sg-shell[data-gnx-theme="system"]{--gnx-bg:#070b18;--gnx-panel:#0f172a;--gnx-panel-strong:#111827;--gnx-text:#e5edf7;--gnx-muted:#9ca3af;--gnx-heading:#f8fafc;--gnx-border:rgba(148,163,184,.2);--gnx-primary:#60a5fa;--gnx-row-hover:rgba(96,165,250,.12);--gnx-header-bg:#0b1220;--gnx-pinned-bg:#080c18;--gnx-shadow:0 24px 70px rgba(4,8,20,.38)}}
.sg-shell[data-gnx-density="compact"]{--gnx-row-height:34px;--gnx-cell-pad:8px}
.sg-shell[data-gnx-density="standard"]{--gnx-row-height:42px;--gnx-cell-pad:12px}
.sg-shell[data-gnx-density="comfortable"]{--gnx-row-height:50px;--gnx-cell-pad:16px}
.sg-toolbar{display:flex;align-items:end;justify-content:space-between;gap:12px;flex-wrap:wrap;padding:12px;border:1px solid var(--gnx-border);border-radius:12px;background:var(--gnx-panel);box-shadow:var(--gnx-shadow)}
.sg-toolbar-copy{display:grid;gap:2px}.sg-toolbar-title{color:var(--gnx-heading);font-weight:900}.sg-toolbar-subtitle,.sg-pager-status{color:var(--gnx-muted);font-size:.86rem}
.sg-toolbar-actions{display:flex;align-items:end;justify-content:flex-end;gap:8px;flex-wrap:wrap}.sg-filter{display:grid;gap:4px}.sg-filter-label{color:var(--gnx-muted);font-size:.72rem;font-weight:900;text-transform:uppercase}
.sg-filter-input,.sg-filter-operator{min-height:34px;padding:0 10px;border:1px solid var(--gnx-border);border-radius:7px;background:var(--gnx-panel-strong);color:var(--gnx-text);font:inherit}.sg-filter-input--short{width:170px}
.sg-toolbar-button,.sg-pivot-clear{min-height:34px;padding:0 11px;border:1px solid color-mix(in srgb,var(--gnx-primary) 45%,var(--gnx-border));border-radius:7px;background:var(--gnx-primary);color:#fff;font:inherit;font-weight:800;cursor:pointer}.sg-toolbar-button--ghost,.sg-pivot-clear{background:var(--gnx-panel-strong);color:var(--gnx-text);border-color:var(--gnx-border)}.sg-toolbar-button:disabled,.sg-pivot-clear:disabled{opacity:.45;cursor:not-allowed}
.sg-grid-workspace{display:grid;grid-template-columns:minmax(0,1fr) auto;min-height:0}.sg-grid-root{display:flex;flex-direction:column;width:100%;height:100%;min-height:280px;border:1px solid var(--gnx-border);border-radius:14px;background:var(--gnx-bg);overflow:auto;box-shadow:var(--gnx-shadow);outline:none}
.sg-header{position:sticky;top:0;z-index:5;min-width:max-content;background:var(--gnx-header-bg);border-bottom:1px solid var(--gnx-border)}.sg-column-header-row,.sg-merged-header-row{display:grid}.sg-column-header-row{min-height:44px}.sg-merged-header-row{min-height:32px;background:#e8f1ff;border-bottom:1px solid #bfdbfe}.sg-shell[data-gnx-theme="dark"] .sg-merged-header-row{background:#13213a;border-bottom-color:rgba(148,163,184,.24)}
.sg-header-cell,.sg-merged-header-cell{display:flex;align-items:center;min-width:0;padding:0 var(--gnx-cell-pad,12px);border-right:1px solid var(--gnx-border);color:var(--gnx-heading);font-size:.78rem;font-weight:900;letter-spacing:.04em;text-transform:uppercase;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.sg-merged-header-cell{justify-content:center;color:#153e90}.sg-shell[data-gnx-theme="dark"] .sg-merged-header-cell{color:#bfdbfe}
.sg-header-actions{display:flex;align-items:center;gap:4px;margin-left:auto}.sg-header-icon-button{display:inline-grid;place-items:center;width:26px;height:26px;border:0;border-radius:6px;background:transparent;color:var(--gnx-muted);cursor:pointer}.sg-header-icon-button:hover,.sg-header-icon-button--active{background:var(--gnx-row-hover);color:var(--gnx-primary)}.sg-resize-handle{align-self:stretch;width:7px;margin-left:4px;cursor:col-resize;border-right:2px solid color-mix(in srgb,var(--gnx-primary) 28%,transparent)}
.sg-body{min-width:max-content}.sg-row{display:grid;position:relative;align-items:center;min-height:var(--gnx-row-height,42px);border-bottom:1px solid var(--gnx-border);transition:background .12s ease}.sg-row:hover{background:var(--gnx-row-hover)}.sg-row[data-selected="true"]{background:color-mix(in srgb,var(--gnx-primary) 16%,transparent)}
.sg-cell{display:flex;align-items:center;gap:6px;min-height:var(--gnx-row-height,42px);padding:0 var(--gnx-cell-pad,12px);border-right:1px solid var(--gnx-border);overflow:hidden;white-space:nowrap;text-overflow:ellipsis;color:var(--gnx-text);background:var(--gnx-bg);font-size:.92rem}.sg-cell--range{background:color-mix(in srgb,var(--gnx-primary) 13%,transparent)}.sg-cell--active{position:relative;z-index:2;outline:2px solid var(--gnx-primary);outline-offset:-2px}.sg-cell--find-match{background:rgba(234,179,8,.18);box-shadow:inset 0 0 0 1px rgba(234,179,8,.7)}.sg-cell-input{width:100%;min-height:30px;border:1px solid var(--gnx-primary);border-radius:6px;background:var(--gnx-panel);color:var(--gnx-text);font:inherit}.sg-advanced-select{position:relative;width:100%}.sg-advanced-select-list{position:absolute;z-index:50;top:calc(100% + 4px);left:0;right:0;display:grid;max-height:190px;overflow:auto;padding:6px;border:1px solid var(--gnx-border);border-radius:10px;background:var(--gnx-panel);box-shadow:var(--gnx-shadow)}.sg-advanced-select-option{min-height:30px;border:0;border-radius:7px;background:transparent;color:var(--gnx-text);text-align:left;cursor:pointer}.sg-advanced-select-option:hover,.sg-advanced-select-option--active{background:var(--gnx-row-hover);color:var(--gnx-primary)}
.sg-row-number,.sg-selection-cell,.sg-selection-header,.sg-row-number-header{display:flex;align-items:center;justify-content:center;min-height:var(--gnx-row-height,42px);border-right:1px solid var(--gnx-border);background:var(--gnx-panel-strong);color:var(--gnx-muted);font-size:.78rem}.sg-selection-checkbox,.sg-cell-checkbox{width:17px;height:17px;accent-color:var(--gnx-primary)}
.sg-row--group{background:var(--gnx-panel-strong);cursor:pointer}.sg-group-row{display:grid;width:100%}.sg-group-label{display:flex;align-items:center;gap:10px;padding:10px 14px;color:var(--gnx-heading);font-size:.82rem;font-weight:800;letter-spacing:.06em;text-transform:uppercase}.sg-group-toggle{color:var(--gnx-primary)}.sg-group-count,.sg-group-summary{color:var(--gnx-muted);font-weight:700;text-transform:none;letter-spacing:0}.sg-group-summary{margin-left:auto}.sg-tree-toggle,.sg-detail-toggle,.sg-row-reorder-button{display:inline-grid;place-items:center;min-width:24px;min-height:24px;border:1px solid var(--gnx-border);border-radius:6px;background:var(--gnx-panel-strong);color:var(--gnx-primary);font:inherit;font-weight:900;cursor:pointer}.sg-row-reorder-controls{display:inline-flex;gap:3px;margin-right:6px;opacity:0;transition:opacity .12s ease}.sg-row:hover .sg-row-reorder-controls{opacity:1}.sg-detail-row{grid-column:1/-1;background:var(--gnx-panel-strong)}.sg-detail-content{padding:14px;color:var(--gnx-text)}
.sg-status-bar{display:flex;align-items:center;gap:12px;flex-wrap:wrap;padding:10px 12px;border:1px solid var(--gnx-border);border-radius:12px;background:var(--gnx-panel);color:var(--gnx-muted);font-size:.78rem;font-weight:800}.sg-status-bar span+span{padding-left:12px;border-left:1px solid var(--gnx-border)}
.sg-side-tools{position:relative;display:flex;align-items:stretch;min-height:280px;border-left:1px solid var(--gnx-border);background:var(--gnx-panel)}.sg-side-tabs{display:grid;grid-auto-rows:minmax(104px,auto);width:42px;background:var(--gnx-panel-strong)}.sg-side-tab{display:grid;place-items:center;gap:8px;min-width:42px;padding:10px 0;border:0;border-bottom:1px solid var(--gnx-border);background:transparent;color:var(--gnx-muted);font:inherit;font-size:.82rem;font-weight:900;writing-mode:vertical-rl;cursor:pointer}.sg-side-tab:hover,.sg-side-tab--active{background:var(--gnx-row-hover);color:var(--gnx-primary)}
.sg-column-chooser{position:relative}.sg-column-chooser-panel,.sg-header-menu,.sg-context-menu,.sg-pivot-panel{position:absolute;z-index:40;min-width:220px;padding:10px;border:1px solid var(--gnx-border);border-radius:12px;background:var(--gnx-panel);box-shadow:var(--gnx-shadow);color:var(--gnx-text)}.sg-header-menu,.sg-context-menu{display:grid;gap:4px}.sg-header-menu-item,.sg-context-menu-item{min-height:32px;border:0;border-radius:7px;background:transparent;color:var(--gnx-text);font:inherit;text-align:left;cursor:pointer}.sg-header-menu-item:hover,.sg-context-menu-item:hover{background:var(--gnx-row-hover)}.sg-header-menu-item:disabled,.sg-context-menu-item:disabled{opacity:.45;cursor:not-allowed}.sg-filter-panel,.sg-advanced-filter-panel{display:grid;gap:10px;min-width:min(720px,calc(100vw - 32px));max-height:min(620px,calc(100vh - 120px));overflow:auto}.sg-filter-panel-row,.sg-advanced-filter-rule{display:grid;grid-template-columns:160px minmax(130px,1fr) minmax(130px,1fr) auto;gap:8px;align-items:center}.sg-filter-panel-label,.sg-advanced-filter-readonly{color:var(--gnx-heading);font-weight:800}.sg-advanced-filter-panel-header,.sg-advanced-filter-group-header{display:flex;align-items:center;justify-content:space-between;gap:10px}.sg-advanced-filter-panel-header span{display:block;color:var(--gnx-muted);font-size:.82rem}.sg-advanced-filter-group,.sg-advanced-filter-conditions{display:grid;gap:8px}.sg-advanced-filter-group{padding:10px;border:1px solid var(--gnx-border);border-radius:10px;background:var(--gnx-panel-strong)}
.sg-ai-command{display:grid;flex:1 1 420px;gap:8px;min-width:min(420px,100%)}.sg-ai-command-form{display:flex;align-items:end;gap:8px}.sg-ai-command-input-wrap{display:grid;flex:1 1 auto;gap:4px;min-width:220px}.sg-ai-command-input{width:100%}.sg-ai-plan,.sg-ai-error{border:1px solid var(--gnx-border);border-radius:8px;background:var(--gnx-panel-strong)}.sg-ai-plan{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px}.sg-ai-plan-copy{display:grid;gap:2px}.sg-ai-plan-copy strong{color:var(--gnx-heading)}.sg-ai-plan-copy span,.sg-ai-plan-actions span{color:var(--gnx-muted);font-size:.82rem}.sg-ai-plan-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.sg-ai-error{padding:8px 10px;color:#dc2626;font-weight:800}
@media(max-width:760px){.sg-toolbar,.sg-toolbar-actions,.sg-ai-command-form,.sg-ai-plan{align-items:stretch;flex-direction:column}.sg-grid-workspace{grid-template-columns:1fr}.sg-side-tools{min-height:auto;border-top:1px solid var(--gnx-border);border-left:0}.sg-side-tabs{grid-auto-flow:column;grid-auto-columns:minmax(110px,1fr);grid-auto-rows:auto;width:100%}.sg-side-tab{min-height:42px;writing-mode:horizontal-tb}.sg-filter,.sg-filter-input,.sg-toolbar-button{width:100%}}
`;

export function injectGridNexaStyles() {
  if (
    typeof document === "undefined" ||
    document.getElementById(runtimeStyleId)
  ) {
    return;
  }

  const style = document.createElement("style");
  style.id = runtimeStyleId;
  style.textContent = runtimeStyles;
  document.head.appendChild(style);
}
